#!/bin/bash

#"$2" < "$3" | valgrind --tool=memcheck --leak-check=full > "$1" 2>&1
valgrind --tool=memcheck --leak-check=full --error-exitcode=7 ./"$2" < "$3" > "$1" > /dev/null 2>&1
if $? -eq 7
then
echo "Memory test failed"
exit 1
fi
echo "Memory test passed"
exit 0