#!bin/bash
if [[ -d logFiles ]]
then
echo "logFiles already exists in this directory"
exit 1
fi
count=1
description=0
sum_success=0
for line in "$1"
description=`awk -F'@' 'NR==${line} {print $1}' "$1"`
name=`awk -F'@' 'NR==${line} {print $2}' "$1"`
in=`awk -F'@' 'NR==${line} {print $3}' "$1"`
out=`awk -F'@' 'NR==${line} {print $4}' "$1"`
echo "${count}: ${descroption}" 
((count++))
res_comp=`testCompilation logFiles/${count}.compile.log name`
res_inout=`testInOut logFiles/${count}.inout.log name in out`
res_mem=`testMemLeaks logFiles/${count}.memory.log name in`
sum_success=((${sum_success}+${res_comp}+${res_inout}+${res_mem}))
done
echo "Num of successful tests= ${sum_success}"
echo "Num of total tests= ((${count}*3))"

