#!/bin/bash
if [ -d logFiles ]
then
echo "logFiles already exists in this directory"
exit 1
fi
mkdir logFiles
count=1
#description=0
sum_success=0
#for line in "$1"
while IFS= read -r line
do
if [ -z "$line" ]
then
break
fi

description=`echo $line | awk -F'@' '{print $1}'`
name=`echo $line | awk -F'@' '{print $2}'`
in=`echo $line | awk -F'@' '{print $3}'`
out=`echo $line | awk -F'@' '{print $4}'`

echo ""$count":"$description"" 
testCompilation logFiles/$count.compile.log $name
res_comp=$?

testInOut logFiles/$count.inout.log $name $in $out
res_inout=$?

testMemLeaks logFiles/$count.memory.log $name $in
res_mem=$?

sum_success="$(( 3+$sum_success-$res_comp-$res_inout-$res_mem ))"
((count++))
done < "$1"
echo "Num of successful tests= ${sum_success}"
echo "Num of total tests= "$((($count-1)*3))""

