#!/bin/bash
#
#****************************************************************
#* function name: testMemLeaks
#* description  : run valgrind to check for memory leaks and
#  ilegal memory access, output log to given file
#* parameter    : log file path, program path, input file path 
#* return value : print if memory test passed or faild
#****************************************************************
valgrind --tool=memcheck --leak-check=full ./"$2" < "$3" > "$1" 2>&1 > /dev/null
noerr=`grep -c "ERROR SUMMARY: 0 errors" "$1"` #check for error statements in log
noleak=`grep -c "no leaks are possible" "$1"`
if (( noerr >0 && noleak >0 )) #if no errors where found return 0 else 1
then
echo "Memory test passed"
exit 0
fi
echo "Memory test failed"
exit 1