#!/bin/bash

valgrind --tool=memcheck --leak-check=full ./"$2" < "$3" > "$1" 2>&1 > /dev/null
noerr=`grep -c "ERROR SUMMARY: 0 errors" "$1"`
noleak=`grep -c "no leaks are possible" "$1"`
if (( noerr >0 && noleak >0 ))
then
echo "Memory test passed"
exit 0
fi
echo "Memory test failed"
exit 1